# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ClothesShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClothesShop
  pod 'Alamofire'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  target 'ClothesShopTests' do
    inherit! :search_paths
    pod 'RxTest'
    pod 'RxBlocking'
  end

end
